version: '3.8'
services:

  redis:
    image: redis
    command: redis-server --appendonly yes
    restart: always
    expose:
      - 6379
    volumes:
      - tl-bot-volume:/data
    networks:
      - tl-bot-network
    environment:
      - REDIS_APPENDFSYNC=always
      - REDIS_REPLICATION_MODE=master

  bot:
    build: .
    links:
      - redis
    networks:
      - tl-bot-network
    environment:
      NODE_ENV: production
      REDIS_URL: redis://redis
      REDIS_PREFIX: 'tl'

networks:
  tl-bot-network:

volumes:
  tl-bot-volume:
